# Generated by Django 5.1.4 on 2025-02-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aunthentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='Image'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hat',
            field=models.ImageField(null=True, upload_to='Image'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tag',
            field=models.CharField(default='default_tag', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
