# Generated by Django 5.1.4 on 2025-02-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aunthentication', '0005_alter_customuser_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tag',
        ),
    ]
