# Generated by Django 5.1.4 on 2025-02-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqly', '0002_post_content_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='Image'),
        ),
    ]
